server:
  port: 8001
  servlet:
    context-path: /heart

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/heart
    username: postgres
    password: fanti
    hikari:
      poolName: heart

  flyway:
    table: db_version_history

